function test_suite = test_hubbard_shift
initTestSuite;
end

function test_3x5
Lx = 5;
Ly = 3;

%% 
index_in = 8;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    7);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    9);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    11);
%% 
index_in = 1;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    13);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    4);
%% 
index_in = 3;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    15);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    6);
%% 
index_in = 13;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    15);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    14);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    10);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    1);
%% 
index_in = 15;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    14);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    13);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    12);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    3);
end

function test_4x4
Lx = 4;
Ly = 4;

%% 
index_in = 1;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    4);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    13);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    5);
%% 
index_in = 4;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    16);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    8);
%% 
index_in = 4;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    16);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    8);
%% 
index_in = 13;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    16);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    14);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    9);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    1);
%% 
index_in = 16;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    15);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    13);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    12);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    4);
%% 
index_in = 10;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    9);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    11);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    6);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    14);
end

function test_5x1
Lx = 5;
Ly = 1;

%% 
index_in = 1;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    2);
%% 
index_in = 5;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    4);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    1);
%% 
index_in = 3;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    4);
end

function test_1x5
Lx = 1;
Ly = 5;

%% 
index_in = 1;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    1);
%% 
index_in = 5;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    4);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    1);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    5);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    5);
%% 
index_in = 3;
assertEqual( ...
    hubbard_shift_up( index_in, Lx, Ly ),...
    2);
assertEqual( ...
    hubbard_shift_down( index_in, Lx, Ly ),...
    4);
assertEqual( ...
    hubbard_shift_left( index_in, Lx, Ly ),...
    3);
assertEqual( ...
    hubbard_shift_right( index_in, Lx, Ly ),...
    3);
end